#!/bin/bash

FACTORS=()

for i in $(seq 1 $1);
  do
   if (( $1 % $i == 0 )); then
       FACTORS+=($i)
   fi
done

for i in $(seq 0 $(#FACTORS[@]);
  do
    echo ${FACTORS[*]}
    if (( i % 2 == 0 )); then
      printf "\n"
    fi
done
